"""Removed the second relation between complain and profile

Revision ID: 10a0f69dc7d9
Revises: 91bf39dba47f
Create Date: 2021-11-24 22:41:47.355317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a0f69dc7d9'
down_revision = '91bf39dba47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complain', 'complained_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('complain_complained_by_fkey', 'complain', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('complain_complained_by_fkey', 'complain', 'profile', ['complained_by'], ['id'])
    op.alter_column('complain', 'complained_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
