"""added post commnet reply model

Revision ID: 12d99582c785
Revises: 83085b18f0b4
Create Date: 2022-01-02 03:05:13.854396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d99582c785'
down_revision = '83085b18f0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('content', sa.String(), nullable=False))
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.add_column('post', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('content', sa.String(), nullable=True))
    op.add_column('post', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('post', sa.Column('up_vote', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('post', sa.Column('down_vote', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'post', 'event', ['event_id'], ['id'])
    op.create_foreign_key(None, 'post', 'profile', ['profile_id'], ['id'])
    op.add_column('reply', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_constraint('reply_post_id_fkey', 'reply', type_='foreignkey')
    op.create_foreign_key(None, 'reply', 'comment', ['comment_id'], ['id'])
    op.drop_column('reply', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.create_foreign_key('reply_post_id_fkey', 'reply', 'post', ['post_id'], ['id'])
    op.drop_column('reply', 'comment_id')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'created_at')
    op.drop_column('post', 'down_vote')
    op.drop_column('post', 'up_vote')
    op.drop_column('post', 'photo')
    op.drop_column('post', 'content')
    op.drop_column('post', 'event_id')
    op.drop_column('post', 'profile_id')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'content')
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
