"""create post comment reply

Revision ID: 18ed1452330b
Revises: 
Create Date: 2022-01-03 19:52:50.445398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ed1452330b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decline', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.drop_constraint('decline_profile_id_fkey', 'decline', type_='foreignkey')
    op.drop_constraint('decline_event_id_fkey', 'decline', type_='foreignkey')
    op.create_foreign_key(None, 'decline', 'payment_pending', ['payment_id'], ['id'])
    op.drop_column('decline', 'profile_id')
    op.drop_column('decline', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decline', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('decline', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'decline', type_='foreignkey')
    op.create_foreign_key('decline_event_id_fkey', 'decline', 'event', ['event_id'], ['id'])
    op.create_foreign_key('decline_profile_id_fkey', 'decline', 'profile', ['profile_id'], ['id'])
    op.drop_column('decline', 'payment_id')
    # ### end Alembic commands ###
