"""change trnx_id column to trnx in pending payments table

Revision ID: 5c3d5fc69238
Revises: a1c28f0af3ab
Create Date: 2022-01-01 19:41:48.476674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3d5fc69238'
down_revision = 'a1c28f0af3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_pending', sa.Column('trnx', sa.String()))
    op.drop_column('payment_pending', 'trnx_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_pending', sa.Column('trnx_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payment_pending', 'trnx')
    # ### end Alembic commands ###
