"""Fixed complain type in complain model

Revision ID: 6c3d1801cbec
Revises: 10a0f69dc7d9
Create Date: 2021-11-24 23:17:37.768031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c3d1801cbec'
down_revision = '10a0f69dc7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complain', sa.Column('category', sa.Enum('CHEATER', 'SCAMER', 'HARASSMENT', 'OTHER', name='complaincategory'), nullable=False))
    op.drop_column('complain', 'complain_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complain', sa.Column('complain_type', postgresql.ENUM('GENERAL', 'HOST', 'ADMIN', name='role'), autoincrement=False, nullable=False))
    op.drop_column('complain', 'category')
    # ### end Alembic commands ###
