"""added relationship between profile, comment, and reply


Revision ID: 704fba091b23
Revises: 12d99582c785
Create Date: 2022-01-03 18:17:42.915663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704fba091b23'
down_revision = '12d99582c785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'profile', ['profile_id'], ['id'])
    op.add_column('reply', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reply', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_column('reply', 'profile_id')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'profile_id')
    # ### end Alembic commands ###
