"""change decline model

Revision ID: 83085b18f0b4
Revises: e9d0ff4fd4ab
Create Date: 2022-01-02 01:42:12.931663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83085b18f0b4'
down_revision = 'e9d0ff4fd4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decline', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.drop_constraint('decline_event_id_fkey', 'decline', type_='foreignkey')
    op.drop_constraint('decline_profile_id_fkey', 'decline', type_='foreignkey')
    op.create_foreign_key(None, 'decline', 'payment_pending', ['payment_id'], ['id'])
    op.drop_column('decline', 'event_id')
    op.drop_column('decline', 'profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decline', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('decline', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'decline', type_='foreignkey')
    op.create_foreign_key('decline_profile_id_fkey', 'decline', 'profile', ['profile_id'], ['id'])
    op.create_foreign_key('decline_event_id_fkey', 'decline', 'event', ['event_id'], ['id'])
    op.drop_column('decline', 'payment_id')
    # ### end Alembic commands ###
