"""Added relationship with profile and complain again

Revision ID: 91bf39dba47f
Revises: f57ecb6fcc5f
Create Date: 2021-11-24 22:40:11.949929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bf39dba47f'
down_revision = 'f57ecb6fcc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complain', 'complained_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'complain', 'profile', ['complained_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complain', type_='foreignkey')
    op.alter_column('complain', 'complained_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
