"""Creating all tablle

Revision ID: a40415c15e8a
Revises: 
Create Date: 2021-12-26 01:32:40.511485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40415c15e8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('hotel_weblink', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'hotel_weblink')
    # ### end Alembic commands ###
