"""added phonenumber column in profile

Revision ID: bac87e1894d3
Revises: 5c3d5fc69238
Create Date: 2022-01-01 20:22:51.789839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac87e1894d3'
down_revision = '5c3d5fc69238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'phone_number')
    # ### end Alembic commands ###
