"""Created complain model and relationship with profile

Revision ID: be2c9bf094e7
Revises: 
Create Date: 2021-11-24 22:12:36.710819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2c9bf094e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'complains')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('complains', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
