"""empty message

Revision ID: c0e800c86f3c
Revises: a40415c15e8a
Create Date: 2021-12-28 23:53:53.882013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e800c86f3c'
down_revision = 'a40415c15e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('fee', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'fee')
    # ### end Alembic commands ###
